In [15]:
import numpy as np
a = np.array([[3, 2, 0], [1, -1, 0], [0, 5, 1]])
b = np.array([2, 4, -1])
c = np.array([0,0,0])
from scipy import linalg
x = linalg.solve(a, c)

In [61]:
from numpy.linalg import matrix_rank, inv, multi_dot
A=np.array([[3, 2, 0], [1, -1, 0], [0, 0, 0]])
b=np.array([[0], [0], [0]])

In [63]:
m, n = A.shape
rank_a = matrix_rank(A)
rank_a_b = matrix_rank(np.concatenate((A, b), axis=1))
print("-----------START-----------")
print("The coefficient matrix A is %s, rank = %d." % (A.shape, rank_a))
if rank_a == m:
    print("The column space of A encompasses R^%d." % m)
else:
    print("The column space of A does not encompass R^%d." % m)
if rank_a < rank_a_b:
    print("rank(A) = %d < %d = rank(A|b), the equation has no solution." % (rank_a, rank_a_b))
else:
    if rank_a == n:
        print("rank(A) = rank(A|b) = %d, the equation has only one solution." % n)

    else:
        if rank_a == n:
            print("rank(A) = rank(A|b) = %d, the equation has only one solution." % n)
            Ar = A
            br = b
            if n < m:
                Ar = Ar[:n]
                br = br[:n]
            Ar_inv = inv(Ar)
            if n < m:
                print("One of the largest sub square of A is T =\n%s" % Ar)
                print("T^-1 =\n%s" % Ar_inv)
                print("x = T^-1 * b = ", end="")
            else:
                print("A^-1 =\n%s" % Ar_inv)
                print("x = A^-1 * b = ", end="")
            x = np.round(multi_dot((Ar_inv, br)), 4).flatten()
            print("%s^T" % x)
        else:
            print("rank(A) = rank(A|b) = %d < %d, the equation has infinitely many solutions." % (rank_a, n))

-----------START-----------
The coefficient matrix A is (3, 3), rank = 2.
The column space of A does not encompass R^3.
rank(A) = rank(A|b) = 2 < 3, the equation has infinitely many solutions.


In [67]:
from sympy import *
from sympy.solvers.solveset import linsolve
x, y, z = symbols('x, y, z')

In [68]:
x, y, z = symbols('x, y, z')
M = Matrix(((1, 1, 1, 1), (1, 1, 2, 3)))
system = A, b = M[:, :-1], M[:, -1]
linsolve(system, x, y, z)

{(-y - 1, y, 2)}

In [ ]:
from random import random

In [169]:
a,b,c,d,e= symbols('a,b,c,d,e')
M = Matrix(((1,1,1,1,1,pb[1]), (list(v)+[0])))
system = A, B = M[:, :-1], M[:, -1]
linsolve(system, a,b,c,d,e)

{(-1.13740804401012*c - 52.5502888452474*d - 1.37321135054469*e + 0.0656535511109588, 0.137408044010123*c + 51.5502888452474*d + 0.373211350544688*e - 0.00111815143772046, c, d, e)}

In [224]:
# Import packages.
import cvxpy as cp

In [258]:
def p_generate(N):
    start=random()
    p=np.zeros(N)
    p[0]=start
    for n in range(1,N-1):
        p[n]=random()*(1-sum(p))
    p[N-1]=1-sum(p)
    return p

In [266]:
pb

array([9.80136767e-01, 1.61568474e-02, 2.68624052e-03, 1.74979607e-04,
       3.19953023e-04, 3.23202010e-04, 1.59689428e-04, 1.07606655e-05,
       2.67138872e-05, 2.97473405e-06, 1.09726393e-06, 4.73712145e-07,
       1.89843868e-07, 5.99381839e-08, 5.03884873e-08, 6.64251766e-10,
       3.91033777e-10, 7.17887259e-12, 3.04359350e-12, 1.10402241e-12,
       4.77549180e-14, 4.27312296e-15, 8.69302432e-14, 2.48200932e-15,
       8.63857154e-16, 6.74716507e-16, 1.13399956e-15, 1.93210263e-17,
       8.06003472e-17, 0.00000000e+00])

In [284]:
x.value

array([0.09111804, 0.05617375, 0.05013166, 0.00103815, 0.13143032,
       0.02997153, 0.02371566, 0.02251419, 0.0025492 , 0.03892156,
       0.05524515, 0.0607277 , 0.04527152, 0.00408974, 0.08539892,
       0.01401824, 0.02139666, 0.01573674, 0.00201311, 0.02208981,
       0.05736662, 0.04423214, 0.03921499, 0.00179269, 0.08384189])

In [279]:
for repeat in range(10):
    N=5
    p0=p_generate(N)
    p1=p_generate(N)
    s0=random()
    s1=1-s0
    pb=s0*p0+s1*p1
    if ~np.all(pb!=0):
        continue
    v=(p0-p1)/pb
    pt=p_generate(N)
    A=np.zeros((3*N,N*N))
    for i in range(N):
        for j in range(N):
            A[i,N*i+j]=1
        for j in range(N):
            A[N+j,N*i+j]=1
        for j in range(N):
            A[2*N+j,N*i+j]=v[i]
    B=np.zeros((3*N))
    for i in range(N):
        B[i]=pb[i]
        B[N+i]=pt[i]
    x = cp.Variable(N*N)
    c=np.ones((N*N,1))
    prob = cp.Problem(cp.Minimize(c.T@x),[A @ x == B,x>=0,x<=1])
    prob.solve()
    print(prob.status)

optimal
optimal
optimal
optimal
optimal
optimal
optimal
optimal
optimal
optimal


In [250]:
A

array([[ 1.,  1.,  1., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ..., nan,  0.,  0.],
       [ 0.,  0.,  0., ...,  0., nan,  0.],
       [ 0.,  0.,  0., ...,  0.,  0., nan]])

In [261]:
x.value

array([7.53758983e-01, 3.46038864e-02, 2.11493118e-03, 1.60093285e-03,
       2.29447208e-03, 5.07155225e-05, 1.30427266e-04, 1.15646459e-05,
       8.92506376e-06, 1.04523680e-07, 5.29720627e-08, 1.04853204e-08,
       5.26959071e-08, 4.50676788e-10, 7.01076224e-10, 2.02528463e-10,
       1.81733259e-10, 2.43551760e-10, 1.36968221e-10, 3.26043154e-13,
       9.88008488e-07, 9.29930113e-06, 4.97642050e-05, 5.81925104e-05,
       4.74633993e-05, 3.07726112e-05, 5.71171642e-05, 8.11263715e-06,
       6.23985919e-06, 4.42081353e-09, 1.95682831e-09, 4.12810456e-10,
       1.94574415e-09, 1.42480326e-11, 2.18341140e-11, 6.55352708e-12,
       5.86887706e-12, 7.87939071e-12, 4.31950636e-12, 9.10959322e-14,
       9.04989206e-02, 2.48682521e-03, 1.77918786e-04, 1.52552103e-04,
       1.86937033e-04, 3.02713599e-05, 5.63932776e-05, 1.03913091e-05,
       8.51992304e-06, 1.67964055e-07, 9.03152170e-08, 2.00128715e-08,
       8.98782803e-08, 9.01668811e-10, 1.38752675e-09, 4.08170496e-10,
      